-- Insert statements for Guardian table
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Ramesh', '9937065416');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Suresh', '9109592736');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Amit', '9612101793');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Vijay', '9930534294');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Arun', '9865918046');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Mahesh', '9601962442');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Rajesh', '9997067886');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Manoj', '9181309356');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Sunil', '9878941302');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Kiran', '9106317867');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Prakash', '9935762632');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Sanjay', '9961214303');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Anil', '9212527993');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Ravi', '9137665707');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Rohit', '9115486127');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Ajay', '9637138671');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Vikas', '9776163570');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Deepak', '9234410937');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Ankit', '9731973282');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Abhishek', '9617097206');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Pankaj', '9309580353');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Naveen', '9848092988');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Naresh', '9534307004');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Lokesh', '9629449378');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Rakesh', '9110430538');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Mukesh', '9752461571');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Santosh', '9102927961');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Vishal', '9506619095');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Akhil', '9528164237');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Sameer', '9759237575');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Kartik', '9567917667');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Gaurav', '9613707409');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Ashok', '9724948555');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Vinod', '9848195581');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Rajan', '9679743878');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Harish', '9721743454');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Suraj', '9726793872');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Yogesh', '9132911536');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Siddharth', '9479006920');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Rahul', '9227938525');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Dev', '9266013598');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Ishaan', '9626422895');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Aman', '9124740770');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Shubham', '9424455291');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Bharat', '9374967033');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Sagar', '9774607311');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Nikhil', '9839953323');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Tarun', '9266421717');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Kabir', '9739818009');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Rohan', '9772454620');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Arjun', '9344102021');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Krishna', '9232000168');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Shyam', '9606836757');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Balram', '9901276439');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Prem', '9656302803');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Mohan', '9812190765');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Dinesh', '9449904480');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Om', '9706031282');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Rajat', '9559903042');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Jatin', '9161162027');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Sanjeev', '9856898675');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Vivek', '9894028348');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Sachin', '9669521594');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Tejas', '9964149448');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Aditya', '9227607922');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Kunal', '9113459539');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Parth', '9255997892');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Harsh', '9138039404');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Raghav', '9490727691');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Varun', '9285409963');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Aryan', '9856040609');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Nitin', '9285381615');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Ravindra', '9717212873');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Madhav', '9705543366');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Narendra', '9546084308');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Hemant', '9149232981');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Rameshwar', '9883013815');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Lakshman', '9362765885');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Govind', '9635644963');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Shankar', '9859030363');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Bhaskar', '9519337966');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Ganesh', '9605953357');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Jagdish', '9246247005');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Sudhir', '9695021019');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Saurabh', '9145667859');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Pranav', '9303016215');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Milind', '9475943369');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Arvind', '9796591626');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Vipin', '9798400601');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Chetan', '9311358395');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Kailash', '9489419585');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Rajendra', '9357908961');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Balaji', '9418088336');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Subodh', '9410594511');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Ashish', '9577064760');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Nilesh', '9929857505');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Roshan', '9352319070');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Anand', '9909235852');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Shiv', '9821337401');
INSERT INTO Guardian (GuardianName, GuardianContact) VALUES ('Atul', '9902454238');


-- Insert statements for Location table (Guardian location)
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (1, 'Delhi', 'DL', '498356');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (2, 'Bangalore', 'KA', '826147');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (3, 'Chennai', 'TN', '130227');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (4, 'Kolkata', 'WB', '613994');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (5, 'Hyderabad', 'TG', '119940');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (6, 'Pune', 'MH', '932610');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (7, 'Ahmedabad', 'GJ', '893351');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (8, 'Jaipur', 'RJ', '666589');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (9, 'Lucknow', 'UP', '120948');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (10, 'Mumbai', 'MH', '998174');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (11, 'Delhi', 'DL', '204285');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (12, 'Bangalore', 'KA', '231162');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (13, 'Chennai', 'TN', '517494');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (14, 'Kolkata', 'WB', '756257');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (15, 'Hyderabad', 'TG', '487410');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (16, 'Pune', 'MH', '254008');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (17, 'Ahmedabad', 'GJ', '930862');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (18, 'Jaipur', 'RJ', '507454');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (19, 'Lucknow', 'UP', '630330');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (20, 'Mumbai', 'MH', '251598');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (21, 'Delhi', 'DL', '331023');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (22, 'Bangalore', 'KA', '545516');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (23, 'Chennai', 'TN', '284629');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (24, 'Kolkata', 'WB', '461057');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (25, 'Hyderabad', 'TG', '385129');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (26, 'Pune', 'MH', '578346');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (27, 'Ahmedabad', 'GJ', '302513');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (28, 'Jaipur', 'RJ', '712296');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (29, 'Lucknow', 'UP', '927803');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (30, 'Mumbai', 'MH', '279749');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (31, 'Delhi', 'DL', '599298');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (32, 'Bangalore', 'KA', '633510');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (33, 'Chennai', 'TN', '257813');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (34, 'Kolkata', 'WB', '167614');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (35, 'Hyderabad', 'TG', '342837');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (36, 'Pune', 'MH', '718306');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (37, 'Ahmedabad', 'GJ', '594425');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (38, 'Jaipur', 'RJ', '259301');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (39, 'Lucknow', 'UP', '478717');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (40, 'Mumbai', 'MH', '941205');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (41, 'Delhi', 'DL', '147695');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (42, 'Bangalore', 'KA', '749673');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (43, 'Chennai', 'TN', '637834');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (44, 'Kolkata', 'WB', '899116');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (45, 'Hyderabad', 'TG', '357602');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (46, 'Pune', 'MH', '211368');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (47, 'Ahmedabad', 'GJ', '240020');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (48, 'Jaipur', 'RJ', '597947');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (49, 'Lucknow', 'UP', '130479');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (50, 'Mumbai', 'MH', '645602');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (51, 'Delhi', 'DL', '971407');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (52, 'Bangalore', 'KA', '974060');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (53, 'Chennai', 'TN', '616436');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (54, 'Kolkata', 'WB', '868960');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (55, 'Hyderabad', 'TG', '142360');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (56, 'Pune', 'MH', '636935');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (57, 'Ahmedabad', 'GJ', '938633');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (58, 'Jaipur', 'RJ', '241421');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (59, 'Lucknow', 'UP', '790190');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (60, 'Mumbai', 'MH', '897239');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (61, 'Delhi', 'DL', '639438');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (62, 'Bangalore', 'KA', '291114');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (63, 'Chennai', 'TN', '719813');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (64, 'Kolkata', 'WB', '574488');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (65, 'Hyderabad', 'TG', '375139');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (66, 'Pune', 'MH', '994339');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (67, 'Ahmedabad', 'GJ', '320422');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (68, 'Jaipur', 'RJ', '327618');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (69, 'Lucknow', 'UP', '754874');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (70, 'Mumbai', 'MH', '868416');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (71, 'Delhi', 'DL', '917498');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (72, 'Bangalore', 'KA', '706655');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (73, 'Chennai', 'TN', '888033');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (74, 'Kolkata', 'WB', '276699');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (75, 'Hyderabad', 'TG', '341226');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (76, 'Pune', 'MH', '885093');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (77, 'Ahmedabad', 'GJ', '401724');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (78, 'Jaipur', 'RJ', '612449');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (79, 'Lucknow', 'UP', '914277');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (80, 'Mumbai', 'MH', '217310');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (81, 'Delhi', 'DL', '187144');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (82, 'Bangalore', 'KA', '401867');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (83, 'Chennai', 'TN', '291809');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (84, 'Kolkata', 'WB', '121762');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (85, 'Hyderabad', 'TG', '237934');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (86, 'Pune', 'MH', '157488');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (87, 'Ahmedabad', 'GJ', '992414');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (88, 'Jaipur', 'RJ', '909312');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (89, 'Lucknow', 'UP', '847772');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (90, 'Mumbai', 'MH', '804627');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (91, 'Delhi', 'DL', '325005');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (92, 'Bangalore', 'KA', '183775');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (93, 'Chennai', 'TN', '199607');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (94, 'Kolkata', 'WB', '717613');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (95, 'Hyderabad', 'TG', '856332');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (96, 'Pune', 'MH', '461790');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (97, 'Ahmedabad', 'GJ', '980698');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (98, 'Jaipur', 'RJ', '230294');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (99, 'Lucknow', 'UP', '182242');
INSERT INTO Location (GuardianID, City, State, ZipCode) VALUES (100, 'Mumbai', 'MH', '768773');

-- Insert statements for Child table
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (1, 'Aarav', '2015-07-15', 9, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (2, 'Vivaan', '2016-09-02', 8, 'M', 'Milk Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (3, 'Reyansh', '2018-04-14', 6, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (4, 'Aadhya', '2017-11-20', 6, 'F', 'Peanut Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (5, 'Aanya', '2015-12-01', 8, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (6, 'Diya', '2017-05-22', 7, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (7, 'Prisha', '2020-03-15', 4, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (8, 'Anaya', '2018-10-07', 6, 'F', 'Milk Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (9, 'Krish', '2019-07-09', 5, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (10, 'Sai', '2018-08-14', 6, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (11, 'Arjun', '2016-11-03', 8, 'M', 'Peanut Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (12, 'Advika', '2015-10-11', 9, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (13, 'Ishita', '2016-03-17', 8, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (14, 'Dev', '2017-07-27', 7, 'M', 'Milk Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (15, 'Riya', '2015-02-19', 9, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (16, 'Aarohi', '2019-01-05', 5, 'F', 'Peanut Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (17, 'Ira', '2018-11-25', 6, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (18, 'Nirvaan', '2017-06-15', 7, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (19, 'Aarush', '2016-05-10', 8, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (20, 'Sara', '2020-10-22', 4, 'F', 'Milk Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (21, 'Anika', '2017-09-19', 7, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (22, 'Yuvaan', '2018-06-30', 6, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (23, 'Aria', '2016-04-03', 8, 'F', 'Peanut Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (24, 'Ayansh', '2019-05-17', 5, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (25, 'Myra', '2018-05-25', 6, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (26, 'Kavya', '2016-08-09', 8, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (27, 'Ayaan', '2017-01-15', 7, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (28, 'Zoya', '2019-03-20', 5, 'F', 'Milk Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (29, 'Ahaan', '2015-06-12', 9, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (30, 'Siddharth', '2018-01-11', 6, 'M', 'Peanut Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (31, 'Arya', '2020-02-02', 4, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (32, 'Aditi', '2015-08-16', 9, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (33, 'Atharv', '2016-11-25', 8, 'M', 'Milk Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (34, 'Kabir', '2017-05-05', 7, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (35, 'Saanvi', '2019-09-11', 5, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (36, 'Veer', '2017-02-24', 7, 'M', 'Peanut Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (37, 'Navya', '2020-01-17', 4, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (38, 'Om', '2018-03-01', 6, 'M', 'Milk Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (39, 'Tara', '2017-04-28', 7, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (40, 'Meera', '2016-06-22', 8, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (41, 'Reeva', '2019-11-30', 4, 'F', 'Peanut Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (42, 'Rishi', '2017-03-15', 7, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (43, 'Pari', '2020-05-25', 4, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (44, 'Krishna', '2018-12-17', 5, 'M', 'Milk Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (45, 'Kiaan', '2017-08-05', 7, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (46, 'Vivaan', '2015-04-13', 9, 'M', 'Peanut Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (47, 'Zara', '2019-04-11', 5, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (48, 'Eva', '2017-06-13', 7, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (49, 'Manan', '2016-10-01', 8, 'M', 'Milk Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (50, 'Ishaan', '2018-02-18', 6, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (51, 'Shaurya', '2017-10-21', 7, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (52, 'Keya', '2019-02-13', 5, 'F', 'Peanut Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (53, 'Neil', '2016-02-10', 8, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (54, 'Rudra', '2020-09-16', 4, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (55, 'Naina', '2015-03-08', 9, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (56, 'Vivaan', '2017-09-05', 7, 'M', 'Milk Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (57, 'Ira', '2018-01-29', 6, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (58, 'Arjun', '2016-07-11', 8, 'M', 'Peanut Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (59, 'Suhana', '2020-12-22', 4, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (60, 'Rohit', '2019-06-16', 5, 'M', 'Milk Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (61, 'Arin', '2015-11-23', 9, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (62, 'Anvi', '2018-09-25', 6, 'F', 'Milk Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (63, 'Rishabh', '2017-03-04', 7, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (64, 'Ishaan', '2015-12-06', 8, 'M', 'Peanut Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (65, 'Vihaan', '2017-12-16', 6, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (66, 'Ananya', '2015-02-23', 9, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (67, 'Aarohi', '2019-03-30', 5, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (68, 'Aryan', '2018-02-28', 6, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (69, 'Dhruv', '2016-04-08', 8, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (70, 'Meera', '2015-05-26', 9, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (71, 'Saanvi', '2020-08-05', 4, 'F', 'Peanut Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (72, 'Kiaan', '2016-12-21', 8, 'M', 'Peanut Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (73, 'Reyansh', '2019-12-28', 4, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (74, 'Aanya', '2018-11-04', 6, 'F', 'Peanut Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (75, 'Arnav', '2017-08-19', 7, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (76, 'Aditi', '2015-02-06', 9, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (77, 'Ahaan', '2019-12-06', 4, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (78, 'Ira', '2016-09-07', 8, 'F', 'Peanut Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (79, 'Naira', '2020-07-29', 4, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (80, 'Vihaan', '2017-08-24', 7, 'M', 'Milk Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (81, 'Anaya', '2020-09-23', 4, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (82, 'Ishika', '2020-04-02', 4, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (83, 'Rian', '2019-05-21', 5, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (84, 'Aditi', '2018-06-04', 6, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (85, 'Samaira', '2017-07-01', 7, 'F', 'Milk Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (86, 'Krishna', '2016-12-19', 8, 'M', 'Peanut Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (87, 'Kabir', '2015-04-10', 9, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (88, 'Anika', '2018-01-05', 6, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (89, 'Neerav', '2017-10-09', 7, 'M', 'Milk Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (90, 'Ishanvi', '2015-03-19', 9, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (91, 'Avni', '2020-02-14', 4, 'F', 'Peanut Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (92, 'Armaan', '2019-10-11', 5, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (93, 'Jiya', '2018-12-06', 6, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (94, 'Rudra', '2016-07-21', 8, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (95, 'Sara', '2015-09-16', 9, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (96, 'Myra', '2017-04-12', 7, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (97, 'Aarush', '2020-06-22', 4, 'M', 'Milk Allergy');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (98, 'Aadhya', '2019-07-18', 5, 'F', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (99, 'Neil', '2016-11-02', 8, 'M', 'None');
INSERT INTO Child (GuardianID, ChildName, ChildDOB, ChildAge, ChildGender, Allergies) VALUES (100, 'Yash', '2015-10-27', 9, 'M', 'Peanut Allergy');




-- Insert statements for Hospital table
INSERT INTO Hospital (HospitalType, H_Name, H_Contact, H_Email) VALUES ('Private', 'Green Valley Hospital', '9939297565', 'greenvalley@hospital.in');
INSERT INTO Hospital (HospitalType, H_Name, H_Contact, H_Email) VALUES ('Private', 'Sunrise Medical Center', '9445690057', 'sunrisemedical@hospital.in');
INSERT INTO Hospital (HospitalType, H_Name, H_Contact, H_Email) VALUES ('Public', 'St. Mary Hospital', '9415537449', 'stmaryshospital@hospital.in');
INSERT INTO Hospital (HospitalType, H_Name, H_Contact, H_Email) VALUES ('Public', 'City General Hospital', '9343939698', 'citygeneral@hospital.in');
INSERT INTO Hospital (HospitalType, H_Name, H_Contact, H_Email) VALUES ('Private', 'Riverfront Healthcare', '9475545213', 'riverfronthc@hospital.in');
INSERT INTO Hospital (HospitalType, H_Name, H_Contact, H_Email) VALUES ('Private', 'Lakeside Medical Institute', '9575371776', 'lakesidemedical@hospital.in');
INSERT INTO Hospital (HospitalType, H_Name, H_Contact, H_Email) VALUES ('Private', 'Evergreen Health Clinic', '9828162803', 'evergreenclinic@hospital.in');
INSERT INTO Hospital (HospitalType, H_Name, H_Contact, H_Email) VALUES ('Private', 'Harmony Care Center', '9939396301', 'harmonycare@hospital.in');
INSERT INTO Hospital (HospitalType, H_Name, H_Contact, H_Email) VALUES ('Private', 'Bright Horizon Hospital', '9896374815', 'brighthorizon@hospital.in');
INSERT INTO Hospital (HospitalType, H_Name, H_Contact, H_Email) VALUES ('Public', 'Royal City Hospital', '9653171375', 'royalcity@hospital.in');


-- Insert statements for Vaccine table
INSERT INTO Vaccine (VaccineName, RecommendedAgeRange, Exclusions, V_Cost, HospitalID) VALUES ('Hepatitis B', '0-4 years', 'Severe allergy to vaccine component', 1400, 3);
INSERT INTO Vaccine (VaccineName, RecommendedAgeRange, Exclusions, V_Cost, HospitalID) VALUES ('Influenza', '6 months and older', 'None', 1300, 9);
INSERT INTO Vaccine (VaccineName, RecommendedAgeRange, Exclusions, V_Cost, HospitalID) VALUES ('Rotavirus', '0-1 years', 'Severe immune deficiency', 1200, 8);
INSERT INTO Vaccine (VaccineName, RecommendedAgeRange, Exclusions, V_Cost, HospitalID) VALUES ('DTaP', '6 months and older', 'Severe allergy to vaccine component', 500, 5);
INSERT INTO Vaccine (VaccineName, RecommendedAgeRange, Exclusions, V_Cost, HospitalID) VALUES ('MMR', '0-4 years', 'Pregnant women', 800, 1);
INSERT INTO Vaccine (VaccineName, RecommendedAgeRange, Exclusions, V_Cost, HospitalID) VALUES ('Polio (IPV)', '0-1 years', 'Severe allergy to vaccine component', 1000, 9);
INSERT INTO Vaccine (VaccineName, RecommendedAgeRange, Exclusions, V_Cost, HospitalID) VALUES ('Hib', '0-1 years', 'Severe allergy to vaccine component', 800, 10);
INSERT INTO Vaccine (VaccineName, RecommendedAgeRange, Exclusions, V_Cost, HospitalID) VALUES ('Pneumococcal Conjugate', '0-1 years', 'None', 500, 2);
INSERT INTO Vaccine (VaccineName, RecommendedAgeRange, Exclusions, V_Cost, HospitalID) VALUES ('Varicella', '1-6 years', 'Severe immune deficiency', 1500, 10);
INSERT INTO Vaccine (VaccineName, RecommendedAgeRange, Exclusions, V_Cost, HospitalID) VALUES ('Hepatitis A', '1-6 years', 'Severe immune deficiency', 1300, 9);
INSERT INTO Vaccine (VaccineName, RecommendedAgeRange, Exclusions, V_Cost, HospitalID) VALUES ('Meningococcal', '1-6 years', 'Severe allergy to vaccine component', 600, 3);
INSERT INTO Vaccine (VaccineName, RecommendedAgeRange, Exclusions, V_Cost, HospitalID) VALUES ('HPV', '0-4 years', 'Severe allergy to vaccine component', 400, 2);
INSERT INTO Vaccine (VaccineName, RecommendedAgeRange, Exclusions, V_Cost, HospitalID) VALUES ('Tdap', '1-6 years', 'Pregnant women', 500, 7);
INSERT INTO Vaccine (VaccineName, RecommendedAgeRange, Exclusions, V_Cost, HospitalID) VALUES ('Shingles', '1-6 years', 'Severe immune deficiency', 1300, 8);
INSERT INTO Vaccine (VaccineName, RecommendedAgeRange, Exclusions, V_Cost, HospitalID) VALUES ('COVID-19', '0-1 years', 'None', 1200, 1);
INSERT INTO Vaccine (VaccineName, RecommendedAgeRange, Exclusions, V_Cost, HospitalID) VALUES ('Pneumonia', '0-1 years', 'Pregnant women', 1300, 8);
INSERT INTO Vaccine (VaccineName, RecommendedAgeRange, Exclusions, V_Cost, HospitalID) VALUES ('Japanese Encephalitis', '1-6 years', 'Pregnant women', 1100, 8);
INSERT INTO Vaccine (VaccineName, RecommendedAgeRange, Exclusions, V_Cost, HospitalID) VALUES ('Rabies', '6 months and older', 'Pregnant women', 600, 9);
INSERT INTO Vaccine (VaccineName, RecommendedAgeRange, Exclusions, V_Cost, HospitalID) VALUES ('Yellow Fever', '0-4 years', 'Severe allergy to vaccine component', 700, 9);
INSERT INTO Vaccine (VaccineName, RecommendedAgeRange, Exclusions, V_Cost, HospitalID) VALUES ('Typhoid', '6 months and older', 'None', 1400, 2);


-- Insert statements for Consent table
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (25, 1, '2023-03-19', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (13, 9, '2023-04-24', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (80, 11, '2023-05-11', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (63, 17, '2023-08-09', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (76, 14, '2023-02-08', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (43, 9, '2023-03-11', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (83, 12, '2023-12-31', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (7, 9, '2023-12-21', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (74, 14, '2023-11-09', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (21, 10, '2023-06-06', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (60, 1, '2023-11-02', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (81, 15, '2023-06-13', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (72, 16, '2023-03-19', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (69, 8, '2023-12-18', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (66, 6, '2023-10-04', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (26, 20, '2023-08-01', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (7, 16, '2023-01-03', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (2, 15, '2023-09-13', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (14, 6, '2023-07-08', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (60, 3, '2023-04-25', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (92, 18, '2023-07-15', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (84, 20, '2023-02-22', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (15, 4, '2023-09-28', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (16, 13, '2023-01-20', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (46, 15, '2023-11-04', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (8, 15, '2023-05-10', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (93, 13, '2023-11-16', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (95, 20, '2023-05-20', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (37, 9, '2023-09-02', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (87, 8, '2023-08-14', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (7, 12, '2023-11-21', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (63, 14, '2023-08-30', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (97, 5, '2023-10-18', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (33, 14, '2023-02-09', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (18, 12, '2023-12-15', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (1, 13, '2023-09-19', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (86, 8, '2023-11-26', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (79, 20, '2023-09-22', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (47, 8, '2023-01-01', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (75, 18, '2023-03-28', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (61, 10, '2023-04-03', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (3, 14, '2023-08-18', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (90, 2, '2023-07-29', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (59, 11, '2023-04-20', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (71, 8, '2023-03-24', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (59, 13, '2023-10-16', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (18, 16, '2023-08-06', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (96, 15, '2023-12-19', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (56, 18, '2023-01-13', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (33, 18, '2023-09-22', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (63, 18, '2023-04-27', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (28, 4, '2023-05-05', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (17, 11, '2023-11-09', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (56, 5, '2023-01-07', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (54, 5, '2023-10-12', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (7, 19, '2023-01-28', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (20, 8, '2023-09-24', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (6, 5, '2023-03-06', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (98, 15, '2023-01-13', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (17, 2, '2023-07-03', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (13, 6, '2023-06-09', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (94, 11, '2023-04-26', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (33, 19, '2023-06-28', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (61, 2, '2023-04-08', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (37, 11, '2023-05-05', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (54, 3, '2023-08-17', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (81, 6, '2023-08-29', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (77, 20, '2023-11-22', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (38, 11, '2023-11-06', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (90, 1, '2023-11-13', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (21, 8, '2023-01-04', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (99, 1, '2023-08-19', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (47, 20, '2023-03-09', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (2, 12, '2023-03-06', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (76, 16, '2023-12-07', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (78, 12, '2023-04-06', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (79, 16, '2023-07-14', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (99, 10, '2023-06-08', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (10, 20, '2023-11-03', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (16, 15, '2023-12-11', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (23, 13, '2023-06-05', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (8, 14, '2023-01-04', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (45, 2, '2023-08-01', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (64, 3, '2023-01-08', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (38, 5, '2023-06-14', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (29, 15, '2023-01-05', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (13, 19, '2023-04-26', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (5, 15, '2023-08-30', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (18, 15, '2023-09-14', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (91, 14, '2023-12-07', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (17, 10, '2023-04-19', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (8, 3, '2023-04-13', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (82, 20, '2023-09-15', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (89, 17, '2023-03-13', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (1, 17, '2023-04-17', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (45, 9, '2023-10-02', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (84, 10, '2023-11-26', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (5, 8, '2023-11-09', 1, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (73, 1, '2023-12-22', 0, 'Consent provided');
INSERT INTO Consent (ChildID, VaccineID, DateGiven, Sign, AdditionalNotes) VALUES (14, 7, '2023-08-30', 1, 'Consent provided');


-- Insert statements for VaccinationHistory table
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (25, 1, '2023-04-14', 'LOT9434', 'Govt Clinic', 76);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (13, 9, '2023-02-12', 'LOT7173', 'Govt Clinic', 87);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (80, 11, '2023-12-20', 'LOT9044', 'Govt Clinic', 49);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (63, 17, '2023-07-23', 'LOT3753', 'Private Health Center', 29);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (76, 14, '2023-10-13', 'LOT2122', 'Govt Clinic', 20);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (43, 9, '2023-04-13', 'LOT5787', 'Govt Clinic', 25);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (83, 12, '2023-06-10', 'LOT6779', 'Private Health Center', 97);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (7, 9, '2023-06-21', 'LOT6846', 'Private Health Center', 8);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (74, 14, '2023-05-22', 'LOT7108', 'Private Health Center', 57);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (21, 10, '2023-05-29', 'LOT1378', 'Private Health Center', 80);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (60, 1, '2023-05-20', 'LOT6247', 'Govt Clinic', 52);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (81, 15, '2023-08-02', 'LOT8935', 'Private Health Center', 87);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (72, 16, '2023-02-27', 'LOT2617', 'Private Health Center', 4);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (69, 8, '2023-08-27', 'LOT7794', 'Govt Clinic', 34);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (66, 6, '2023-01-11', 'LOT4256', 'Govt Clinic', 5);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (26, 20, '2023-07-06', 'LOT4088', 'Govt Clinic', 28);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (7, 16, '2023-02-09', 'LOT7935', 'Govt Clinic', 89);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (2, 15, '2023-12-27', 'LOT4539', 'Govt Clinic', 79);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (14, 6, '2023-01-30', 'LOT5893', 'Private Health Center', 20);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (60, 3, '2023-09-14', 'LOT1184', 'Private Health Center', 93);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (92, 18, '2023-12-16', 'LOT5781', 'Private Health Center', 6);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (84, 20, '2023-01-04', 'LOT6206', 'Govt Clinic', 72);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (15, 4, '2023-02-01', 'LOT9715', 'Govt Clinic', 56);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (16, 13, '2023-09-30', 'LOT8482', 'Private Health Center', 42);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (46, 15, '2023-10-22', 'LOT5363', 'Private Health Center', 37);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (8, 15, '2023-09-15', 'LOT2300', 'Govt Clinic', 65);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (93, 13, '2023-12-19', 'LOT8362', 'Govt Clinic', 60);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (95, 20, '2023-12-21', 'LOT1354', 'Private Health Center', 39);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (37, 9, '2023-01-28', 'LOT7653', 'Govt Clinic', 26);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (87, 8, '2023-02-19', 'LOT8917', 'Govt Clinic', 9);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (7, 12, '2023-09-11', 'LOT7773', 'Private Health Center', 79);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (63, 14, '2023-01-04', 'LOT7359', 'Private Health Center', 90);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (97, 5, '2023-04-28', 'LOT5239', 'Private Health Center', 57);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (33, 14, '2023-12-04', 'LOT7938', 'Govt Clinic', 9);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (18, 12, '2023-11-06', 'LOT1921', 'Private Health Center', 2);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (1, 13, '2023-10-17', 'LOT4705', 'Private Health Center', 49);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (86, 8, '2023-08-04', 'LOT8352', 'Govt Clinic', 76);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (79, 20, '2023-12-22', 'LOT2556', 'Private Health Center', 57);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (47, 8, '2023-01-18', 'LOT2689', 'Private Health Center', 96);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (75, 18, '2023-10-31', 'LOT4550', 'Govt Clinic', 3);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (61, 10, '2023-03-28', 'LOT9454', 'Govt Clinic', 81);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (3, 14, '2023-02-20', 'LOT5810', 'Govt Clinic', 12);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (90, 2, '2023-03-05', 'LOT3458', 'Govt Clinic', 61);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (59, 11, '2023-07-15', 'LOT7901', 'Govt Clinic', 57);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (71, 8, '2023-11-29', 'LOT7324', 'Private Health Center', 68);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (59, 13, '2023-01-23', 'LOT4626', 'Private Health Center', 41);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (18, 16, '2023-06-18', 'LOT9519', 'Private Health Center', 15);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (96, 15, '2023-01-13', 'LOT4493', 'Private Health Center', 16);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (56, 18, '2023-05-09', 'LOT1406', 'Govt Clinic', 26);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (33, 18, '2023-12-26', 'LOT5550', 'Govt Clinic', 12);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (63, 18, '2023-04-04', 'LOT5250', 'Private Health Center', 74);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (28, 4, '2023-09-08', 'LOT7908', 'Private Health Center', 6);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (17, 11, '2023-11-24', 'LOT7230', 'Private Health Center', 93);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (56, 5, '2023-07-28', 'LOT4932', 'Private Health Center', 34);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (54, 5, '2023-10-30', 'LOT6713', 'Private Health Center', 66);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (7, 19, '2023-01-15', 'LOT4112', 'Private Health Center', 18);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (20, 8, '2023-11-20', 'LOT9794', 'Private Health Center', 14);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (6, 5, '2023-08-29', 'LOT2353', 'Private Health Center', 83);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (98, 15, '2023-11-29', 'LOT6174', 'Govt Clinic', 80);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (17, 2, '2023-10-28', 'LOT4063', 'Private Health Center', 92);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (13, 6, '2023-05-08', 'LOT7383', 'Private Health Center', 15);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (94, 11, '2023-10-13', 'LOT6137', 'Govt Clinic', 43);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (33, 19, '2023-08-04', 'LOT6744', 'Govt Clinic', 36);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (61, 2, '2023-10-17', 'LOT7556', 'Govt Clinic', 73);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (37, 11, '2023-12-26', 'LOT3877', 'Govt Clinic', 2);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (54, 3, '2023-11-01', 'LOT1060', 'Private Health Center', 29);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (81, 6, '2023-07-04', 'LOT4663', 'Govt Clinic', 90);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (77, 20, '2023-05-11', 'LOT8129', 'Private Health Center', 44);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (38, 11, '2023-12-28', 'LOT3526', 'Govt Clinic', 74);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (90, 1, '2023-07-14', 'LOT2656', 'Govt Clinic', 80);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (21, 8, '2023-03-28', 'LOT5609', 'Private Health Center', 46);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (99, 1, '2023-07-25', 'LOT2519', 'Private Health Center', 22);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (47, 20, '2023-03-12', 'LOT6349', 'Private Health Center', 64);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (2, 12, '2023-01-09', 'LOT1782', 'Private Health Center', 51);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (76, 16, '2023-07-04', 'LOT4722', 'Govt Clinic', 60);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (78, 12, '2023-05-21', 'LOT5582', 'Govt Clinic', 84);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (79, 16, '2023-06-05', 'LOT1240', 'Private Health Center', 77);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (99, 10, '2023-10-20', 'LOT8868', 'Private Health Center', 34);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (10, 20, '2023-07-15', 'LOT8235', 'Govt Clinic', 84);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (16, 15, '2023-09-10', 'LOT1821', 'Private Health Center', 50);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (23, 13, '2023-01-15', 'LOT6852', 'Govt Clinic', 93);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (8, 14, '2023-05-17', 'LOT3455', 'Private Health Center', 64);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (45, 2, '2023-08-17', 'LOT5845', 'Govt Clinic', 87);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (64, 3, '2023-08-13', 'LOT7914', 'Govt Clinic', 51);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (38, 5, '2023-04-10', 'LOT8518', 'Private Health Center', 85);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (29, 15, '2023-02-13', 'LOT7399', 'Private Health Center', 85);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (13, 19, '2023-06-02', 'LOT6560', 'Private Health Center', 46);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (5, 15, '2023-08-22', 'LOT5675', 'Govt Clinic', 62);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (18, 15, '2023-08-01', 'LOT1532', 'Govt Clinic', 55);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (91, 14, '2023-08-01', 'LOT7130', 'Govt Clinic', 3);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (17, 10, '2023-11-09', 'LOT7644', 'Private Health Center', 90);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (8, 3, '2023-08-01', 'LOT4465', 'Private Health Center', 23);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (82, 20, '2023-11-07', 'LOT3192', 'Govt Clinic', 91);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (89, 17, '2023-09-05', 'LOT4298', 'Govt Clinic', 95);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (1, 17, '2023-07-10', 'LOT5126', 'Private Health Center', 25);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (45, 9, '2023-03-18', 'LOT8208', 'Govt Clinic', 76);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (84, 10, '2023-03-30', 'LOT7693', 'Govt Clinic', 92);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (5, 8, '2023-12-05', 'LOT5301', 'Private Health Center', 27);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (73, 1, '2023-11-26', 'LOT6133', 'Private Health Center', 40);
INSERT INTO VaccinationHistory (ChildID, VaccineID, FirstDate, LotNumber, Provider, LocationID) VALUES (14, 7, '2023-02-03', 'LOT3023', 'Private Health Center', 18);




-- Insert statements for Inventory table
INSERT INTO Inventory (Inv_Name, Inv_Contact, QuantityRemaining, HospitalID) VALUES ('MediCare', '9747610425', 60, 10);
INSERT INTO Inventory (Inv_Name, Inv_Contact, QuantityRemaining, HospitalID) VALUES ('PharmaPlus', '9588972666', 380, 4);
INSERT INTO Inventory (Inv_Name, Inv_Contact, QuantityRemaining, HospitalID) VALUES ('HealthGuard', '9337276965', 95, 1);
INSERT INTO Inventory (Inv_Name, Inv_Contact, QuantityRemaining, HospitalID) VALUES ('WellnessHub', '9655998769', 71, 3);
INSERT INTO Inventory (Inv_Name, Inv_Contact, QuantityRemaining, HospitalID) VALUES ('BioMedix', '9153393826', 336, 6);
INSERT INTO Inventory (Inv_Name, Inv_Contact, QuantityRemaining, HospitalID) VALUES ('MedicoPath', '9951175060', 281, 4);
INSERT INTO Inventory (Inv_Name, Inv_Contact, QuantityRemaining, HospitalID) VALUES ('CuraCare', '9367778371', 63, 1);
INSERT INTO Inventory (Inv_Name, Inv_Contact, QuantityRemaining, HospitalID) VALUES ('ApexHealth', '9997184483', 317, 5);
INSERT INTO Inventory (Inv_Name, Inv_Contact, QuantityRemaining, HospitalID) VALUES ('VitaPlus', '9238985764', 253, 4);
INSERT INTO Inventory (Inv_Name, Inv_Contact, QuantityRemaining, HospitalID) VALUES ('NeoLife', '9385349083', 196, 9);
INSERT INTO Inventory (Inv_Name, Inv_Contact, QuantityRemaining, HospitalID) VALUES ('OptiCare', '9104847053', 449, 4);
INSERT INTO Inventory (Inv_Name, Inv_Contact, QuantityRemaining, HospitalID) VALUES ('HealthPrime', '9916900117', 496, 5);
INSERT INTO Inventory (Inv_Name, Inv_Contact, QuantityRemaining, HospitalID) VALUES ('MediSphere', '9715038296', 472, 4);
INSERT INTO Inventory (Inv_Name, Inv_Contact, QuantityRemaining, HospitalID) VALUES ('VitalCare', '9161057146', 99, 8);
INSERT INTO Inventory (Inv_Name, Inv_Contact, QuantityRemaining, HospitalID) VALUES ('CareWell', '9198374151', 324, 1);
INSERT INTO Inventory (Inv_Name, Inv_Contact, QuantityRemaining, HospitalID) VALUES ('MediTrust', '9128993792', 109, 10);
INSERT INTO Inventory (Inv_Name, Inv_Contact, QuantityRemaining, HospitalID) VALUES ('PharmaLine', '9126869881', 176, 7);
INSERT INTO Inventory (Inv_Name, Inv_Contact, QuantityRemaining, HospitalID) VALUES ('LifeGuard', '9320954056', 165, 10);
INSERT INTO Inventory (Inv_Name, Inv_Contact, QuantityRemaining, HospitalID) VALUES ('BioCare', '9507534757', 105, 6);
INSERT INTO Inventory (Inv_Name, Inv_Contact, QuantityRemaining, HospitalID) VALUES ('HealthPlus', '9488157698', 281, 6);


-- Insert statements for VaccineInventoryLocation table
INSERT INTO VaccineInventoryLocation (InvID, City, State, ZipCode) VALUES (1, 'Mumbai', 'Maharashtra', '836411');
INSERT INTO VaccineInventoryLocation (InvID, City, State, ZipCode) VALUES (2, 'Delhi', 'NCR', '590868');
INSERT INTO VaccineInventoryLocation (InvID, City, State, ZipCode) VALUES (3, 'Bangalore', 'Karnataka', '722231');
INSERT INTO VaccineInventoryLocation (InvID, City, State, ZipCode) VALUES (4, 'Hyderabad', 'Telangana', '659156');
INSERT INTO VaccineInventoryLocation (InvID, City, State, ZipCode) VALUES (5, 'Chennai', 'Tamil Nadu', '391905');
INSERT INTO VaccineInventoryLocation (InvID, City, State, ZipCode) VALUES (6, 'Kolkata', 'West Bengal', '332448');
INSERT INTO VaccineInventoryLocation (InvID, City, State, ZipCode) VALUES (7, 'Pune', 'Maharashtra', '329581');
INSERT INTO VaccineInventoryLocation (InvID, City, State, ZipCode) VALUES (8, 'Ahmedabad', 'Gujarat', '177169');
INSERT INTO VaccineInventoryLocation (InvID, City, State, ZipCode) VALUES (9, 'Jaipur', 'Rajasthan', '869325');
INSERT INTO VaccineInventoryLocation (InvID, City, State, ZipCode) VALUES (10, 'Lucknow', 'Uttar Pradesh', '571433');
